SUPABASE_URL = "https://oyyywfwufogknghzyeov.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95eXl3Znd1Zm9na25naHp5ZW92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0OTcwMDcsImV4cCI6MjA4OTA3MzAwN30.D0FknXlUKi7AQhuGvIKLgUdOhfkruE2Wphf6We0BU-0"   
OWNER_CIN = "1248795849"
MONCASH_NUM = "+50947385663"
OwnSpace_Password = "OwnerSpace2025"
UNIBANK US Money account
UNIBANK_ACCOUNT = "105-2016-16594727"
BACKEND_API_URL = " oyyywfwufogknghzyeov" 
BACKEND_API_KEY = "sb_publishable_7vOy6TP69i0sgTaoP6Iilg_gvyXfwFr"
MONCASH_MODE = "live"
