SUPABASE_URL="https://oyyywfwufogknghzyeov.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95eXl3Znd1Zm9na25naHp5ZW92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0OTcwMDcsImV4cCI6MjA4OTA3MzAwN30.D0FknXlUKi7AQhuGvIKLgUdOhfkruE2Wphf6We0BU-0"
